using AbpIssueDistributedEventsInUnitTest.EntityFrameworkCore;
using Xunit;

namespace AbpIssueDistributedEventsInUnitTest.EntityFrameworkCore;

public class AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreFixture>
{

}
