using Volo.Abp;

namespace AbpIssueDistributedEventsInUnitTest.EntityFrameworkCore;

public abstract class AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreTestBase : AbpIssueDistributedEventsInUnitTestTestBase<AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreTestModule>
{

}
