using Xunit;

namespace AbpIssueDistributedEventsInUnitTest.EntityFrameworkCore;

[CollectionDefinition(AbpIssueDistributedEventsInUnitTestTestConsts.CollectionDefinitionName)]
public class AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreCollection : ICollectionFixture<AbpIssueDistributedEventsInUnitTestEntityFrameworkCoreFixture>
{

}
